/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Asistent;
import domen.Predmet;
import gui.komponente.TblModel;
//import gui.komponente.Predmet;
import java.util.ArrayList;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.table.TableColumn;
import kontroler.Kontroler;

/**
 *
 * @author vujke
 */
public class Index extends javax.swing.JFrame {
    
    TblModel tbl;
    Kontroler kontroler;
    /**
     * Creates new form Index
     */
    public Index() {
        initComponents();
        kontroler = Kontroler.getInstance();
        srediTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbtUbaci = new javax.swing.JButton();
        jbtIzbaci = new javax.swing.JButton();
        jbtSacuvaj = new javax.swing.JButton();
        jbtPrikazi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jbtUbaci.setText("+");
        jbtUbaci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtUbaciActionPerformed(evt);
            }
        });

        jbtIzbaci.setText("-");

        jbtSacuvaj.setText("Sacuvaj");
        jbtSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSacuvajActionPerformed(evt);
            }
        });

        jbtPrikazi.setText("Prikazi");
        jbtPrikazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPrikaziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtPrikazi, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jbtIzbaci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbtUbaci, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jbtSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jbtUbaci)
                        .addGap(31, 31, 31)
                        .addComponent(jbtIzbaci)
                        .addGap(34, 34, 34)
                        .addComponent(jbtSacuvaj)
                        .addGap(26, 26, 26)
                        .addComponent(jbtPrikazi)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtUbaciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtUbaciActionPerformed
        // TODO add your handling code here:
       //TblModel tbl1 = (TblModel) jTable1.getModel();
        tbl.napraviRed();
       
    }//GEN-LAST:event_jbtUbaciActionPerformed

    private void jbtSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSacuvajActionPerformed
        // TODO add your handling code here:
        kontroler.sacuvajAsistente(tbl.vratiAsistenteIzMemorije());
    }//GEN-LAST:event_jbtSacuvajActionPerformed

    private void jbtPrikaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPrikaziActionPerformed
        // TODO add your handling code here
        int red = jTable1.getSelectedRow();
 
        Asistent a = tbl.vratiAsistenteIzMemorije().get(red);
        Predmet p = a.getPredmet();
        int semestar = p.getSemestar();
        String naziv = p.getNaziv();
        int brBodova = p.getBrBodova();
        
        PrikazForma pf = new PrikazForma(p);
        JDialog jd = new JDialog(this, "Prikaz predmeta");
        
        jd.add(pf);
        jd.pack();
        jd.setVisible(true);
        
        
        //a.get
        
    }//GEN-LAST:event_jbtPrikaziActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtIzbaci;
    private javax.swing.JButton jbtPrikazi;
    private javax.swing.JButton jbtSacuvaj;
    private javax.swing.JButton jbtUbaci;
    // End of variables declaration//GEN-END:variables

    private void srediTabelu() {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
       tbl = new TblModel(new ArrayList<>());
       jTable1.setModel(tbl);
       
       JComboBox cbPredmet = new JComboBox(kontroler.vratiListuPredmeta().toArray());
       //cbPredmet.addItem();
       TableColumn tcPredmeti = jTable1.getColumnModel().getColumn(4);
       tcPredmeti.setCellEditor(new DefaultCellEditor(cbPredmet));
    }
}
