/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Polozio;
import javax.swing.JDialog;
import kontroler.Kontroler;

/**
 *
 * @author vujke
 */
public class Detalji extends javax.swing.JPanel {
    
    Polozio polozio;
    Kontroler kontroler;
    /**
     * Creates new form Detalji
     */
//    public Detalji() {
//        initComponents();
//    }

    Detalji(Polozio vratiPolozioIzMemorije) {
        initComponents();
        this.polozio = vratiPolozioIzMemorije;
        kontroler  = Kontroler.getInstance();
        ucitajDetalje();
//throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtObrisi = new javax.swing.JButton();
        jLabel = new javax.swing.JLabel();

        jbtObrisi.setText("Obrisi");
        jbtObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtObrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jbtObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtObrisi)
                    .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(139, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtObrisiActionPerformed
        // TODO add your handling code here:
        //kontroler.obrisiPrijavu(polozio);
        Potvrda pot = new Potvrda(polozio);
        JDialog dialog = new JDialog();
        dialog.add(pot);
        dialog.pack();
        dialog.setVisible(true);
    }//GEN-LAST:event_jbtObrisiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel;
    private javax.swing.JButton jbtObrisi;
    // End of variables declaration//GEN-END:variables

    private void ucitajDetalje() {
        jLabel.setText(polozio.getPredmet()+" "+polozio.getOcena());
        //mrzi me previse realno xD
//throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
