/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Predmet;
import gui.komponente.TblModel;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JFrame;
import kontroler.Kontroler;

/**
 *
 * @author vujke
 */
public class RadSaStudentima extends javax.swing.JPanel {
    TblModel tbl;
    Kontroler kontroler;
    /**
     * Creates new form RadSaStudentima
     */
    public RadSaStudentima() {
        initComponents();
        srediTabelu();
        kontroler = Kontroler.getInstance();
        ucitajPredmete();
        //srediTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbPredmeti = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbtDedatli = new javax.swing.JButton();

        jcbPredmeti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPredmetiActionPerformed(evt);
            }
        });

        jLabel1.setText("Predmet");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jbtDedatli.setText("Detalji");
        jbtDedatli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDedatliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(24, 24, 24)
                        .addComponent(jcbPredmeti, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jbtDedatli, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addGap(45, 45, 45))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbPredmeti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jbtDedatli)))
                .addGap(45, 45, 45))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jcbPredmetiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPredmetiActionPerformed
        // TODO add your handling code here:
        Predmet p = (Predmet) jcbPredmeti.getSelectedItem();
        //tbl.prikaziStudente(p);
        tbl.prikaziStudene(kontroler.vratiSaPolozenim(p));
    }//GEN-LAST:event_jcbPredmetiActionPerformed

    private void jbtDedatliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDedatliActionPerformed
        // TODO add your handling code here:
        int red =jTable1.getSelectedRow();
        Detalji det = new Detalji(tbl.vratiPolozioIzMemorije(red));
       // JDialog dialog = new JDialog(this, "Detalji");
       //Detalji det = new Detalji();
       JDialog dialog = new JDialog();
       dialog.add(det);
       dialog.pack();
       dialog.setVisible(true);
    }//GEN-LAST:event_jbtDedatliActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtDedatli;
    private javax.swing.JComboBox jcbPredmeti;
    // End of variables declaration//GEN-END:variables

    private void ucitajPredmete() {
        jcbPredmeti.removeAllItems();
        List<Predmet> predmeti =  kontroler.vratiSvePredmete();
        for (Predmet predmet : predmeti) {
            jcbPredmeti.addItem(predmet);
        }
//throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void srediTabelu() {
        tbl = new TblModel(new ArrayList<>());
        jTable1.setModel(tbl);
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
