/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Zadatak;
import domen.Zaposleni;
import gui.komponente.TblModel;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import kontroler.Kontroler;

/**
 *
 * @author vujke
 */
public class FormaDodajZadatak extends javax.swing.JPanel {
    TblModel tbl;
    Kontroler kontroler; 
    /**
     * Creates new form FormaDodajZadatak
     */
    public FormaDodajZadatak(TblModel tbl) {
        initComponents();
        kontroler = Kontroler.getInstance();
        ucitajZaposlene();
        this.tbl = tbl;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtSifraZadatka = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtOpis = new javax.swing.JTextField();
        jtxtNaziv = new javax.swing.JTextField();
        jtxtDatum = new javax.swing.JTextField();
        jcbZaposleni = new javax.swing.JComboBox();
        jbtSacuvaj = new javax.swing.JButton();
        jbtOdustani = new javax.swing.JButton();

        jtxtSifraZadatka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSifraZadatkaActionPerformed(evt);
            }
        });

        jLabel1.setText("sifra zadatka:");

        jLabel2.setText("datum:");

        jLabel3.setText("naziv:");

        jLabel4.setText("opis:");

        jLabel5.setText("zaposleni:");

        jtxtOpis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtOpisActionPerformed(evt);
            }
        });

        jtxtNaziv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNazivActionPerformed(evt);
            }
        });

        jtxtDatum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDatumActionPerformed(evt);
            }
        });

        jcbZaposleni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbZaposleniActionPerformed(evt);
            }
        });

        jbtSacuvaj.setText("Sacuvaj");
        jbtSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSacuvajActionPerformed(evt);
            }
        });

        jbtOdustani.setText("Odustani");
        jbtOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtOdustaniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtOdustani)
                    .addComponent(jbtSacuvaj)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jcbZaposleni, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtxtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtxtSifraZadatka, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtxtOpis, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtxtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtSifraZadatka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jtxtOpis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcbZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbtSacuvaj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtOdustani)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtSifraZadatkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSifraZadatkaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSifraZadatkaActionPerformed

    private void jtxtOpisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtOpisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtOpisActionPerformed

    private void jtxtNazivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNazivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNazivActionPerformed

    private void jtxtDatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDatumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDatumActionPerformed

    private boolean validacija(String naziv, String opis, String datumStr){
        if(naziv.length()==0 || opis.length()==0 || datumStr.length()==0){
            JOptionPane.showMessageDialog(jbtOdustani, "Nije sve popunjeno");
            return false;
        }
        
        return true;
    }
    
    private void jbtSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSacuvajActionPerformed
        try {
            // TODO add your handling code here:
            String sifraZadatka = jtxtSifraZadatka.getText();
            String naziv = jtxtNaziv.getText();
            String opis = jtxtOpis.getText();
            String datumStr = jtxtDatum.getText();
            
            DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
            Date datum = df.parse(datumStr);
            
            boolean val = validacija(naziv, opis, datumStr);
            
            if(val){
            
            Zaposleni zaposleni = (Zaposleni) jcbZaposleni.getSelectedItem();
            
            Zadatak z = new Zadatak(sifraZadatka, datum, naziv, opis, zaposleni);
            
            tbl.dodajRed(z);
            }
        } catch (ParseException ex) {
            Logger.getLogger(FormaDodajZadatak.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(jbtOdustani, "Datum nije u odgovarajucem formatu");
        }
    }//GEN-LAST:event_jbtSacuvajActionPerformed

    private void jbtOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtOdustaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtOdustaniActionPerformed

    private void jcbZaposleniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbZaposleniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbZaposleniActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbtOdustani;
    private javax.swing.JButton jbtSacuvaj;
    private javax.swing.JComboBox jcbZaposleni;
    private javax.swing.JTextField jtxtDatum;
    private javax.swing.JTextField jtxtNaziv;
    private javax.swing.JTextField jtxtOpis;
    private javax.swing.JTextField jtxtSifraZadatka;
    // End of variables declaration//GEN-END:variables

    private void ucitajZaposlene() {
        try {
             List<Zaposleni> zaposleni = kontroler.vratiListuZaposlenih();
                jcbZaposleni.removeAllItems();
        
            for (Zaposleni zap : zaposleni) {
               jcbZaposleni.addItem(zap);
            }
        } catch (Exception e) {
        }
       
    //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
