/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Zadatak;
import gui.komponente.TblModel;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import kontroler.Kontroler;

/**
 *
 * @author vujke
 */
public class Index extends javax.swing.JFrame {
    TblModel tbl;
    Kontroler kontroler;
    /**
     * Creates new form Index
     */
    public Index() {
        initComponents();
        kontroler = Kontroler.getInstance();
        
        srediTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbtDodajNoviZadatak = new javax.swing.JButton();
        jbtObrisiZadatak = new javax.swing.JButton();
        jbtSacuvaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jbtDodajNoviZadatak.setText("Dodaj Novi Zadatak");
        jbtDodajNoviZadatak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDodajNoviZadatakActionPerformed(evt);
            }
        });

        jbtObrisiZadatak.setText("Obrisi Zadatak");
        jbtObrisiZadatak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtObrisiZadatakActionPerformed(evt);
            }
        });

        jbtSacuvaj.setText("Sacuvaj");
        jbtSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jbtDodajNoviZadatak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtObrisiZadatak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtSacuvaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jbtDodajNoviZadatak)
                        .addGap(18, 18, 18)
                        .addComponent(jbtObrisiZadatak)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtSacuvaj)))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSacuvajActionPerformed
        // TODO add your handling code here:
        kontroler.obrisiZadatkeIzBaze();
        List<Zadatak> listaZadataka = tbl.vratiZadatkeIzMemorije();
        kontroler.upisiZadatkeIzMemorije(tbl.vratiZadatkeIzMemorije());
        tbl.fireTableDataChanged();
        JOptionPane.showConfirmDialog(rootPane, "Upisano");
        
    }//GEN-LAST:event_jbtSacuvajActionPerformed

    private void jbtObrisiZadatakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtObrisiZadatakActionPerformed
        // TODO add your handling code here:
        int rowIndex = jTable1.getSelectedRow();
        List<Zadatak> listaZadataka = tbl.vratiZadatkeIzMemorije();
        
        for (int i = 0; i < listaZadataka.size(); i++) {
            if(i==rowIndex){
                listaZadataka.remove(listaZadataka.get(i));
                tbl.fireTableDataChanged();
            }
        }
    }//GEN-LAST:event_jbtObrisiZadatakActionPerformed

    private void jbtDodajNoviZadatakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDodajNoviZadatakActionPerformed
        // TODO add your handling code here:
        FormaDodajZadatak frm = new FormaDodajZadatak(tbl);
        JDialog dialog = new JDialog(this, "Dodaj zadatak");
          dialog.add(frm);
          dialog.pack();
          dialog.setVisible(true);
    }//GEN-LAST:event_jbtDodajNoviZadatakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtDodajNoviZadatak;
    private javax.swing.JButton jbtObrisiZadatak;
    private javax.swing.JButton jbtSacuvaj;
    // End of variables declaration//GEN-END:variables

    private void srediTabelu() {
        tbl = new TblModel(new ArrayList<>());
        List<Zadatak> zadaciBaza = kontroler.vratiListuZadataka();
        tbl.popuniTabelu(zadaciBaza);
        jTable1.setModel(tbl);
        
        
        
    
    //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    //public void updateTabela(){
        
    //}
}
