/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forme;

import Kontroler.Kontroler;
import domen.Zadatak;
import domen.Zaposleni;
import gui.komponenete.TblModelZadatak;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author vujke
 */
public class NoviZadaci extends javax.swing.JPanel {
    
    TblModelZadatak tbl;
    Kontroler kontroler;
    /**
     * Creates new form NoviZadaci
     */
    public NoviZadaci(TblModelZadatak tbl) {
        initComponents();
        kontroler = Kontroler.vratiInstancuKontrolera();
        ucitajZaposlene();
        this.tbl = tbl;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtSifra1 = new javax.swing.JTextField();
        jtxtNaziv = new javax.swing.JTextField();
        jtxtOpis = new javax.swing.JTextField();
        jtxtDatum = new javax.swing.JTextField();
        jcbZaposleni = new javax.swing.JComboBox();
        jbtSacuvaj = new javax.swing.JButton();
        jbtObrisi = new javax.swing.JButton();

        jLabel1.setText("Sifra");

        jLabel2.setText("Naziv");

        jLabel3.setText("Opis");

        jLabel4.setText("Datum");

        jLabel5.setText("Zaposleni");

        jtxtSifra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSifra1ActionPerformed(evt);
            }
        });

        jtxtNaziv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNazivActionPerformed(evt);
            }
        });

        jtxtOpis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtOpisActionPerformed(evt);
            }
        });

        jtxtDatum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDatumActionPerformed(evt);
            }
        });

        jcbZaposleni.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbZaposleni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbZaposleniActionPerformed(evt);
            }
        });

        jbtSacuvaj.setText("Sacuvaj");
        jbtSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSacuvajActionPerformed(evt);
            }
        });

        jbtObrisi.setText("Obrisi");
        jbtObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtObrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jtxtSifra1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtxtNaziv, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtOpis, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtDatum, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbZaposleni, 0, 334, Short.MAX_VALUE))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtSifra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtOpis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jbtSacuvaj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtObrisi)
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtSifra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSifra1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSifra1ActionPerformed

    private void jtxtNazivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNazivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNazivActionPerformed

    private void jtxtOpisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtOpisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtOpisActionPerformed

    private void jtxtDatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDatumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDatumActionPerformed

    private void jcbZaposleniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbZaposleniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbZaposleniActionPerformed

    private void jbtSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSacuvajActionPerformed
        // TODO add your handling code here:
        try {
            String sifra = jtxtSifra1.getText();
            String naziv = jtxtNaziv.getText();
            String opis = jtxtOpis.getText();

            String datumSTR = jtxtDatum.getText();
            DateFormat df = new SimpleDateFormat("mm/dd/yyyy");

            Date datum = df.parse(datumSTR);
            Zaposleni zap = (Zaposleni) jcbZaposleni.getSelectedItem();
            //String sifraZap = zap.getSifra();

            Zadatak z = new Zadatak(sifra, datum, naziv, opis, zap);

            tbl.dodajRed(z);
            
            
        } catch (ParseException ex) {
            //Logger.getLogger(NoviZadatak.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(jcbZaposleni, "Nije dobar datum");
        } 

    }//GEN-LAST:event_jbtSacuvajActionPerformed

    private void jbtObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtObrisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtObrisiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbtObrisi;
    private javax.swing.JButton jbtSacuvaj;
    private javax.swing.JComboBox jcbZaposleni;
    private javax.swing.JTextField jtxtDatum;
    private javax.swing.JTextField jtxtNaziv;
    private javax.swing.JTextField jtxtOpis;
    private javax.swing.JTextField jtxtSifra1;
    // End of variables declaration//GEN-END:variables

    private void ucitajZaposlene() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        try {
            //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            
            List<Zaposleni> zaposleni =  kontroler.vratiListuZaposlenih();
            
            jcbZaposleni.removeAllItems();
            
            for (Zaposleni zap : zaposleni) {
                jcbZaposleni.addItem(zap);
                
            }
        } catch (Exception ex) {
            Logger.getLogger(NoviZadatak.class.getName()).log(Level.SEVERE, null, ex);
            
            
        }
    }
}
